version: '3.7'

services:

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/test
    volumes:
      - neo4j-data:/data
      - ./import:/var/lib/neo4j/import

volumes:
  neo4j-data:
